# TCL File Generated by Component Editor 15.1
# Sat Feb 24 10:36:01 CET 2018
# DO NOT MODIFY


# 
# codec "codec" v1.0
# M.S. & R.R. 2018.02.24.10:36:01
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module codec
# 
set_module_property DESCRIPTION ""
set_module_property NAME codec
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MisPerifericos
set_module_property AUTHOR "M.S. & R.R."
set_module_property DISPLAY_NAME codec
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_SoundMIDI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Sound_module.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/Sound_module.vhd
add_fileset_file UCau_out.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/UCau_out.vhd
add_fileset_file au_out.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/au_out.vhd
add_fileset_file sin_DDS.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/sin_DDS.vhd
add_fileset_file sin256rom_pkg.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/work/sin256rom_pkg.vhd
add_fileset_file avalon_Sonido_v1.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/avalon_Sonido_v1.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_SoundMIDI
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Sound_module.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/Sound_module.vhd
add_fileset_file UCau_out.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/UCau_out.vhd
add_fileset_file au_out.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/au_out.vhd
add_fileset_file sin_DDS.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/sin_DDS.vhd
add_fileset_file sin256rom_pkg.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/work/sin256rom_pkg.vhd
add_fileset_file avalon_Sonido_v1.vhd VHDL PATH hardware/TecMIDI_v2/Modelsim_avalon_sinDDS/avalon_Sonido_v1.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 cs chipselect Input 1
add_interface_port avalon_slave_0 wr_n write_n Input 1
add_interface_port avalon_slave_0 addr address Input 2
add_interface_port avalon_slave_0 wr_data writedata Input 32
add_interface_port avalon_slave_0 rd_data readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end aud_daclrck export Input 1


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock
set_interface_property conduit_end_1 associatedReset reset_sink
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 aud_bclk export Input 1


# 
# connection point conduit_end_2
# 
add_interface conduit_end_2 conduit end
set_interface_property conduit_end_2 associatedClock clock
set_interface_property conduit_end_2 associatedReset reset_sink
set_interface_property conduit_end_2 ENABLED true
set_interface_property conduit_end_2 EXPORT_OF ""
set_interface_property conduit_end_2 PORT_NAME_MAP ""
set_interface_property conduit_end_2 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_2 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_2 aud_dacdat export Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink clr_n reset_n Input 1

